### ISSUE TITLE
Sync throws error when badly configured settings

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1359]
I just put random data in my settings to get apinf.io running. Noticed that an error is getting thrown:

```
I20160805-12:00:00.015(3) (synced-cron-server.js:63) SyncedCron: Starting "Sync API Umbrella Users and API Backends".
I20160805-12:00:00.587(3) (synced-cron-server.js:63) SyncedCron: Exception "Sync API Umbrella Users and API Backends" TypeError: Cannot read property 'length' of null
    at new ApiUmbrellaError (packages/apinf_api-umbrella/server/apiUmbrellaError.js:23:1)
    at Object.self.adminApi.v1.apiUsers.getUsers (packages/apinf_api-umbrella/server/apiUmbrellaWeb.js:321:1)
    at [object Object].syncApiUmbrellaUsers (server/methods/apiUmbrella.js:9:58)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:1624:18
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Server.apply (packages/ddp-server/livedata_server.js:1623:45)
    at Server.call (packages/ddp-server/livedata_server.js:1566:17)
    at Object.job (server/startup.js:14:16)
    at packages/percolate_synced-cron/synced-cron-server.js:218:1
```

Would be good to put the relevant code in a try-catch?

**Comment by brylie** [comment]
@bajiat we can close this issue, as it is likely no longer relevant. At least, we are no longer using synced cron to sync the Proxy Backends.

**Comment by ilarimikkonen** [comment]
before next, stabilization
