### ISSUE TITLE
Exception in subscription apiAuthorizedUsersPublicDetails

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1880]
On a fresh database, the following error is visible in the server console:

```
Exception from sub apiAuthorizedUsersPublicDetails id 3ByDFjW9c3bMAF4mQ TypeError: Cannot read property 'authorizedUserIds' of undefined
     at Subscription.<anonymous> (users/collection/server/publications.js:23:40)
     at packages/matb33_collection-hooks.js:307:21
     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
     at Subscription._handler (packages/matb33_collection-hooks.js:306:28)
     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1026:17)
     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
     at packages/ddp-server/livedata_server.js:551:43
```

**Comment by bajiat** [comment]
Please check if this can this be reproduced.

**Comment by brylie** [comment]
Does not seem to occur on a fresh database any longer.
