### ISSUE TITLE
Exception from sub currentApiLogo id

### ISSUE THREAD

**Issue by shaliko** [apinf/platform#2527]
Server: staging.apinf.io
Version: 0.44.0
URL: Main page https://staging.apinf.io

```
=> Starting app on port 3000...
{"line":"106","file":"percolate_migrations.js","message":"Migrations: Not migrating, control is locked.","time":{"$date":1493883702291},"level":"info"}
Exception from sub currentApiLogo id tJXA9aHT4853eAC7a Error: Match error: Expected string, got null
    at exports.check (packages/check.js:57:15)
    at [object Object].<anonymous> (apis/logo/server/publications.js:15:3)
    at packages/matb33_collection-hooks.js:307:21
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at [object Object]._handler (packages/matb33_collection-hooks.js:306:28)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
    at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
    at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:853:9)
    at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
    at packages/ddp-server/livedata_server.js:559:43
```

**Comment by brylie** [comment]
@shaliko would you try unlocking the migrations collection?

https://github.com/percolatestudio/meteor-migrations#errors

Then, we can better see whether this is a migration bug, which it likely is.

**Comment by marla-singer** [comment]
@brylie The main idea is
```
Exception from sub currentApiLogo id tJXA9aHT4853eAC7a Error: Match error: Expected string, got null
```

**Comment by brylie** [comment]
@marla-singer right, but I am just wondering if running the migration might mitigate this issue.

**Comment by shaliko** [comment]
@brylie @marla-singer Migrated, after migration no issue, but I will observe logs for 1 day.

**Comment by shaliko** [comment]
@brylie @marla-singer I am closing that bug, no more exceptions on staging.
